package fr.uga.m1miage.pc.joueur.enums;


public enum StrategieEnum {
    DONNANT_DONNANT,
    TOUJOURS_COOPERER,
    TOUJOURS_TRAHIR,
    RANCUNIER,
    ALEATOIRE,
    DONNANT_DONNANT_ALEATOIRE,

    DONNANT_POUR_DEUX_DONNANTS_ALEATOIRE,

    SONDEUR_NAIF,

    SONDEUR_REPENTANT,

    PACIFICATEUR_NAIF,

    VRAI_PACIFICATEUR,

    PAVLOV,
    PAVLOV_ALEATOIRE;
}
